
[id]
    languageName = "Indonesia"
    LanguageCode = "id-ID"
    title        = "Perpustakaan Yuros"
    staticDir    = "static_id"
    weight       = 0
[en]
    languageName = "English"
    LanguageCode = "en-US"
    title        = "Yuros Libraries"
    staticDir    = "static_en"
    weight       = 1


