# Konfigurasi Produksi Yuros
baseURL = "https://almuhdilkarim.github.io/"
theme  = "informos"
defaultContentLanguage = "id"

[taxonomies]
  category  = "categories"
  tag       = "tags"
  podcat    = "podcats"
  podtag    = "podtags"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10