author      = "Al Muhdil Karim"
headnav     = "Navigasi"
headacc     = "Personalisasi"
favicon     = "brand/favicon.ico"
brandlogo   = "brand/yuros.png"
appstore    = "image/badges/app-store-badge.png"
playstore   = "image/badges/google-play-badge.png"