# theme.toml template for a Hugo theme

name        = "Informos"
license     = "Copyright"
description = "Themes for yoros library "
homepage    = "yuros.org"
tags        = ["e-learning", "opac", "database", "ebooks"]
features    = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.00"

[author]
  name = "Al Muhdil Karim"
  homepage = "https://almuhdilkarim.com"
